version: '3.5'
services:
  #### node_test used for auto test with node
  test:
    container_name: test
    image: chrishsieh/node_test_web_driver
    command: npm test -- --hostname=selenium --baseUrl=http://${_DEV_VIRTUAL_HOST:-dev.localtest.me}
    volumes:
      - ./test/specs:/app/test/specs
