version: '3.5'
services:
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      - db-dev-volume:/var/lib/mysql
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      - crm_secrets

  php-dev:
    container_name: php-dev
    build: ./build/php-apache-dev
    links:
      - db
    environment:
      - MYSQL_DB_HOST=db
      ##### if set will do git reset --hard $GIT_RESET(origin/master; origin/master src; adfca5d) #####
      ##### , others do git checkout $GIT_CHECKOUT #####
      - GIT_RESET=origin/master
      ##### if set and $GIT_RESET is null will do git checkout $GIT_CHECKOUT(origin/master; origin/master src; adfca5d) #####
      - GIT_CHECKOUT=origin/master src
      - VIRTUAL_HOST=dev.localtest.me   ##### need modify  #####
      - VIRTUAL_ROOT=/var/www/CRM/src
#      - ENABLE_HSTS=true
#      - ENABLE_ACME=true               ##### letsencrypt setting
    volumes:
      - ./content/:/var/www/CRM/src     ##### php code
      - content-dev:/var/www            ##### builded code update volume
      - ./keys/acme:/acmecerts          #acme.sh install folder
      - ./keys/certs:/etc/ssl/certs     #certs folder
      - ./setting/php-apache-dev/www.conf:/etc/apache2/sites-available/www.conf:ro
      - ./setting/php-apache-dev/ssl.conf:/etc/apache2/sites-available/ssl.conf:ro
      - ./setting/php-apache-dev/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      - ./setting/php-apache-dev/crmsetup:/usr/local/prechk
      - ./secrets/BuildConfig.json:/var/www/CRM/BuildConfig.json    ##### need modify  #####
      - ./log/php-dev:/usr/local/var/log    #debug use.
 #      - ./setting/nginx/dns_dynu.sh:/acme.sh/dnsapi/dns_dynu.sh   # fix dynu.sh issue
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - crm_secrets
      - ssl
#      - dns_api
secrets:
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
#  dns_api:
#    file: ./secrets/dns_api.json           ##### need modify  #####
  ssl:
    file: ./secrets/ssl-dev.json            ##### need modify  #####

volumes:
  db-dev-volume: null
  content-dev: null