version: '3.5'
services:
  #### nginx serivces
  web:
    container_name: web
    image: chrishsieh/nginx-proxy:latest
    environment:
      - DEFAULT_HOST=${_DEV_DEFAULT_HOST:-myapp.localtest.me}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam-volume:/etc/nginx/dhparam/
      - ./setting/nginx/vhost.d/:/etc/nginx/vhost.d:ro
      - ./setting/nginx/stream.d/:/etc/nginx/stream.d
      - ./setting/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./setting/nginx/nginx.tmpl:/app/nginx.tmpl:ro
      - ${_DEV_CERTS_FOLDER:-./keys}/acme:/acmecerts                            #acme.sh install folder
      - ${_DEV_CERTS_FOLDER:-./keys}/certs:/etc/nginx/certs                     #certs folder
      - ./setting/nginx/updatessl.sh:/app/prechk
#      - ./setting/nginx/updatessl-debug.sh:/app/prechk    #debug use.
#      - ./setting/nginx/Procfile-debug:/app/Procfile:ro   #debug nginx mode.
      - ${_DEV_LOG_FOLDER:-./log}/nginx/:/var/log/nginx/                      #log
    restart: always
    secrets:
      - dns_api
      - ssl
    networks:
      default:
        #### setting for services call web server by host name
        aliases:
          - ${_DEV_VIRTUAL_HOST:-dev.localtest.me}

  #### db use mysql as database
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      #### database saved volume
      - db-dev-volume:/var/lib/mysql
      #### pre-script before service start, init CRM database
      - ./setting/sql/sql_setup:/usr/local/prechk
    ports:
      - "3306:3306"
    secrets:
      #### database secret setting
      - crm_secrets

  #### php-fpm serivces
  php:
    container_name: php
    image: chrishsieh/php-fpm-dev:latest
    links:
      - db
    environment:
      ##### do git ${GIT_CMD} #####
      GIT_CMD: ${_DEV_GIT_CMD}
      MYSQL_DB_HOST: db
      ##### locale only used for alpine OS #####
      LC_ALL: ${_DEV_ALPINE_LC_ALL:-en_US}
      VIRTUAL_HOST: ${_DEV_VIRTUAL_HOST:-dev.localtest.me}
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_ROOT: /var/www/CRM/src
      VIRTUAL_PORT: 9000
      ##### nginx debug trace #####
      DEBUG_MODE: ${_DEV_NGINX_DEBUG_MODE:-"false"}
      ENABLE_HSTS: ${_DEV_ENABLE_HSTS:-false}
      ENABLE_ACME: ${_DEV_ENABLE_ACME:-false}                ##### letsencrypt setting
    volumes:
      #### code
      - code:/var/www
      #### php setting
      - ./setting/php-dev/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./setting/php-dev/php.ini:/usr/local/etc/php/php.ini:ro
      #### xdebug setting
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      #### pre-script before service start, setting CRM
      - ./setting/php-dev/crmsetup:/usr/local/prechk
      #### CRM buildConfig setting
      - ${_DEV_CRM_BUILD_CONFIG:-./secrets/BuildConfig.json}:/var/BuildConfig.json
      #### php log file
      - ${_DEV_LOG_FOLDER:-./log}/php-dev:/usr/local/var/log    #### debug use.
    secrets:
      - crm_secrets

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  #### unison used for sync code to windows host
  unison:
    container_name: unison
    #### version need same as windows unison version.
    image: eugenmayer/unison:2.51.2.1
    command: "/entrypoint.sh supervisord"
    environment:
      APP_VOLUME: "/unison"
      UNISON_ARGS: "-socket 5000"
      OWNER_UID: 33
      UNISON_WATCH_ARGS: ""
      UNISON_SRC: ""
      UNISON_DEST: ""
      HOST_VOLUME: ""
      MONIT_ENABLE: "false"
    volumes:
      - code:/unison
    ports:
      - "5000:5000"
    restart: on-failure

  #### selenium used for web access
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    shm_size: 2g
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
#    volumes:
#      - /dev/shm:/dev/shm

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"

secrets:
  #### database secret setting
  crm_secrets:
    file: ${_DEV_CRM_SRCRETS:-./secrets/crm_sql_secrets.json}
  #### for DNS server auto api setting.
  dns_api:
    file: ${_DEV_DNS_API_SRCRETS:-./secrets/dns_api.json}
  #### cert setting.
  ssl:
    file: ${_DEV_SSL_SRCRETS:-./secrets/ssl-dev.json}

volumes:
  #### database data volume
  db-dev-volume: null
  #### volume used for docker link
  dhparam-dev-volume: null
  #### code volume used for sync
  code: null
