version: '3.5'
services:
  web:
    container_name: web
#    build: ./build/nginx-proxy
    image: chrishsieh/nginx-proxy:latest
    environment:
      - DEFAULT_HOST=myapp.localtest.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam-volume:/etc/nginx/dhparam/
      - ./setting/nginx/vhost.d/:/etc/nginx/vhost.d:ro
      - ./setting/nginx/stream.d/:/etc/nginx/stream.d
      - ./setting/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./setting/nginx/nginx.tmpl:/app/nginx.tmpl:ro
      - ./setting/nginx/updatessl.sh:/app/prechk
      - ./keys/acme:/acmecerts                                  #acme.sh install folder
      - ./keys/certs:/etc/nginx/certs                           #certs folder
    restart: always
    secrets:
      - ssl

  php:
    container_name: php
    image: php:fpm-alpine
    environment:
      - VIRTUAL_HOST=myapp.localtest.me
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_PORT=9000
#      - HTTPS_METHOD=nohttps
    volumes:
      - ./html:/var/www/html

secrets:
  ssl:
    file: ./secrets/ssl-test.json  ##### need modify  #####

volumes:
  dhparam-volume: null

