version: '3.5'
services:
  web:
    container_name: web
    image: chrishsieh/nginx-proxy:latest
    environment:
      - DEFAULT_HOST=myapp.localtest.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam-volume:/etc/nginx/dhparam/
      - ./setting/nginx/vhost.d/:/etc/nginx/vhost.d:ro
      - ./setting/nginx/stream.d/:/etc/nginx/stream.d
      - ./setting/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./setting/nginx/nginx.tmpl:/app/nginx.tmpl:ro
      - ./keys/acme:/acmecerts                            #acme.sh install folder
      - ./keys/certs:/etc/nginx/certs                     #certs folder
      - ./setting/nginx/updatessl-debug.sh:/app/prechk    #debug use.
      - ./setting/nginx/Procfile-debug:/app/Procfile:ro   #debug nginx mode.
      - ./log/nginx/:/var/log/nginx/                      #log
    restart: always
    secrets:
#      - dns_api
      - ssl

  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      - db-dev-volume:/var/lib/mysql
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      - crm_secrets

  php:
    container_name: php
    build:
      context: ./build/php
      args:
        ##### CODE_VERSION avaiable value: latest, alpine-latest
        CODE_VERSION: latest
        ##### do git checkout $GIT_CHECKOUT(origin/master; origin/master src; adfca5d; tags/3.0.10) #####
        GIT_CHECKOUT: origin/master
    image: php-nginx-dev:latest
    links:
      - db
    environment:
      - MYSQL_DB_HOST=db
      - LC_ALL=en_US                    ##### locale only used for alpine OS #####
      - VIRTUAL_HOST=dev.localtest.me   ##### need modify  #####
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_ROOT=/var/www/CRM/src
      - VIRTUAL_PORT=9000
#      - DEBUG_MODE=true                 ##### nginx debug trace #####
#      - ENABLE_HSTS=true
#      - ENABLE_ACME=true                ##### letsencrypt setting
    volumes:
      - ./content/:/var/www/CRM           ##### code
      - ./setting/php-dev/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      - ./setting/php-dev/crmsetup:/usr/local/prechk
      - ./secrets/BuildConfig.json:/var/www/BuildConfig.json    ##### need modify  #####
      - ./log/php-dev:/usr/local/var/log    #### debug use.
    secrets:
      - crm_secrets

secrets:
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
#  dns_api:
#    file: ./secrets/dns_api.json           ##### need modify  #####
  ssl:
    file: ./secrets/ssl-dev.json            ##### need modify  #####

volumes:
  db-dev-volume: null
  dhparam-volume: null
