version: '3.5'
services:
  web:
    container_name: web
#    build: ./build/nginx-proxy
    image: chrishsieh/nginx-proxy:latest
    environment:
      - DEFAULT_HOST=myapp.localtest.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam-volume:/etc/nginx/dhparam/
      - ./setting/nginx/vhost.d/:/etc/nginx/vhost.d:ro
      - ./setting/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./setting/nginx/updatessl.sh:/app/prechk      #if debug need disable this.
#      - ./setting/nginx/updatessl-debug.sh:/app/prechk #debug use.
      - ./setting/nginx/dns_dynu.sh:/acme.sh/dnsapi/dns_dynu.sh # fix dynu.sh issue
      - ./keys/acme:/acmecerts #acme.sh install folder
      - ./keys/certs:/etc/nginx/certs #certs folder
#      - ./setting/nginx/Procfile-debug:/app/Procfile:ro  #debug nginx mode. /setting/nginx/vhost.d/default need enable error_log /var/debug/error.log debug;
#      - ./log/nginx:/var/debug #debug use.
    restart: always
    secrets:
#      - dns_api
      - ssl
#    network_mode: "host"

  db:
    container_name: db
#    build: ./build/mysql
    image: chrishsieh/mysql:latest
    volumes:
      - db-volume:/var/lib/mysql
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      - crm_secrets

  php:
    container_name: php
#    build: ./build/php-fpm
    image: chrishsieh/php-fpm:latest
    links:
      - db
    environment:
      - MYSQL_DB_HOST=db
      - LC_ALL=en_US            ##### locale  #####
      - VIRTUAL_HOST=myapp.localtest.me  ##### need modify  #####
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_ROOT=/var/www/CRM/src
      - VIRTUAL_PORT=9000
#      - ENABLE_ACME=true       ##### letsencrypt setting
      - ENABLE_HSTS=true
    volumes:
#      - ./content/www:/var/www # php file debug
      - content:/var/www
      - ./setting/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./setting/php/crmsetup:/usr/local/prechk
#      - ./log/php:/usr/local/var/log  #debug use.
    secrets:
      - crm_secrets

secrets:
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
#  dns_api:
#    file: ./secrets/dns_api.json  ##### need modify  #####
  ssl:
    file: ./secrets/ssl.json  ##### need modify  #####

volumes:
  db-volume: null
  dhparam-volume: null
  content: null

