version: '3.5'
services:
  #### nginx serivces
  web:
    container_name: web
    image: chrishsieh/nginx-proxy:latest
    environment:
      - DEFAULT_HOST=myapp.localtest.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - dhparam-volume:/etc/nginx/dhparam/
      - ./setting/nginx/vhost.d/:/etc/nginx/vhost.d:ro
      - ./setting/nginx/stream.d/:/etc/nginx/stream.d
      - ./setting/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./setting/nginx/nginx.tmpl:/app/nginx.tmpl:ro
      - ./keys/acme:/acmecerts                            #acme.sh install folder
      - ./keys/certs:/etc/nginx/certs                     #certs folder
      - ./setting/nginx/updatessl-debug.sh:/app/prechk    #debug use.
      - ./setting/nginx/Procfile-debug:/app/Procfile:ro   #debug nginx mode.
      - ./log/nginx/:/var/log/nginx/                      #log
    restart: always
    secrets:
#      - dns_api
      - ssl

  #### db use mysql as database
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      #### database saved volume
      - db-dev-volume:/var/lib/mysql
      #### pre-script before service start, init CRM database
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      #### database secret setting
      - crm_secrets

  #### php-fpm serivces
  php:
    container_name: php
    image: chrishsieh/php-fpm-dev:latest
    links:
      - db
    environment:
      ##### do git checkout $GIT_CHECKOUT(origin/master; origin/master src; adfca5d; tags/3.0.10) #####
      GIT_CHECKOUT: -b master origin/master
      MYSQL_DB_HOST: db
      LC_ALL: en_US                    ##### locale only used for alpine OS #####
      VIRTUAL_HOST: dev.localtest.me   ##### need modify  #####
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_ROOT: /var/www/CRM/src
      VIRTUAL_PORT: 9000
#      DEBUG_MODE: true                 ##### nginx debug trace #####
#      ENABLE_HSTS: true
#      ENABLE_ACME: true                ##### letsencrypt setting
    volumes:
      #### code
      - code:/var/www
      #### php setting
      - ./setting/php-dev/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./setting/php-dev/php.ini:/usr/local/etc/php/php.ini:ro
      #### xdebug setting
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      #### pre-script before service start, setting CRM
      - ./setting/php-dev/crmsetup:/usr/local/prechk
      #### CRM buildConfig setting
      - ./secrets/BuildConfig.json:/var/BuildConfig.json    ##### need modify  #####
      #### php log file
      - ./log/php-dev:/usr/local/var/log    #### debug use.
    secrets:
      - crm_secrets

  #### unison used for sync code to windows host
  unison:
    container_name: unison
    #### version need same as windows unison version.
    image: eugenmayer/unison:2.51.2.1
    depends_on:
      - php
    command: "/entrypoint.sh supervisord"
    environment:
      APP_VOLUME: "/unison"
      UNISON_ARGS: "-socket 5000"
      OWNER_UID: 33
      UNISON_WATCH_ARGS: ""
      UNISON_SRC: ""
      UNISON_DEST: ""
      HOST_VOLUME: ""
      MONIT_ENABLE: "false"
    volumes:
      - code:/unison
    ports:
      - "5000:5000"

secrets:
  #### database secret setting
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
  #### for DNS server auto api setting.
#  dns_api:
#    file: ./secrets/dns_api.json           ##### need modify  #####
  #### cert setting.
  ssl:
    file: ./secrets/ssl-dev.json            ##### need modify  #####

volumes:
  #### database data volume
  db-dev-volume: null
  #### volume used for docker link
  dhparam-volume: null
  #### code volume used for sync
  code: null
