version: '3.5'
services:
  #### db use mysql as database
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      #### database saved volume
      - db-dev-volume:/var/lib/mysql
      #### pre-script before service start, init CRM database
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      #### database secret setting
      - crm_secrets

  #### php run php and apache serivces
  php:
    container_name: php
    image: chrishsieh/php-apache-dev:latest
    links:
      - db
    environment:
      ##### do git checkout $GIT_CHECKOUT(origin/master; origin/master src; adfca5d; tags/3.0.10) #####
      GIT_CHECKOUT: -b master origin/master
      MYSQL_DB_HOST: db
      VIRTUAL_HOST: dev.localtest.me   ##### need modify  #####
      VIRTUAL_ROOT: /var/www/CRM/src
#      ENABLE_HSTS: true
#      ENABLE_ACME: true               ##### letsencrypt setting
    volumes:
      #### code
      - code:/var/www
      #### certs
      - ./keys/acme/:/acmecerts               #acme.sh install folder
      - ./keys/certs/:/etc/apache2/certs      #certs folder
      #### apache setting
      - ./setting/php-apache-dev/www.conf:/etc/apache2/sites-available/www.conf:ro
      - ./setting/php-apache-dev/ssl.conf:/etc/apache2/sites-available/ssl.conf:ro
      #### php setting
      - ./setting/php-apache-dev/php.ini:/usr/local/etc/php/php.ini:ro
      #### xdebug setting
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      #### pre-script before service start, setting CRM
      - ./setting/php-apache-dev/crmsetup:/usr/local/prechk
      #### pre-script before service start, setting certs
      - ./setting/php-apache-dev/app/:/app
      #### CRM buildConfig setting
      - ./secrets/BuildConfig.json:/var/BuildConfig.json    ##### need modify  #####
      #### php log file
      - ./log/php-dev/:/usr/local/var/log     #debug use.
      #### others
 #      - ./setting/nginx/dns_dynu.sh:/acme.sh/dnsapi/dns_dynu.sh   # fix dynu.sh issue
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - crm_secrets
      - ssl
#      - dns_api

  #### unison used for sync code to windows host
  unison:
    container_name: unison
    #### version need same as windows unison version.
    image: eugenmayer/unison:2.51.2.1
    depends_on:
      - php
    command: "/entrypoint.sh supervisord"
    environment:
      APP_VOLUME: "/unison"
      UNISON_ARGS: "-socket 5000"
      OWNER_UID: 33
      UNISON_WATCH_ARGS: ""
      UNISON_SRC: ""
      UNISON_DEST: ""
      HOST_VOLUME: ""
      MONIT_ENABLE: "false"
    volumes:
      - code:/unison
    ports:
      - "5000:5000"

secrets:
  #### database secret setting
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
  #### for DNS server auto api setting.
#  dns_api:
#    file: ./secrets/dns_api.json           ##### need modify  #####
  #### cert setting.
  ssl:
    file: ./secrets/ssl-dev.json            ##### need modify  #####

volumes:
  #### database data volume
  db-dev-volume: null
  #### code volume used for sync
  code: null
