version: '3.5'
services:
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      - db-dev-volume:/var/lib/mysql
      - ./setting/sql/sql_setup:/usr/local/prechk
    secrets:
      - crm_secrets

  php:
    container_name: php
    build:
      context: ./build/php
      args:
        IMG_VERSION: php-apache-dev
        CODE_VERSION: latest
        CMD_STRING: apache2-foreground
    image: php-apache-dev:latest
    links:
      - db
    environment:
      ##### do git checkout $GIT_CHECKOUT(origin/master; origin/master src; adfca5d; tags/3.0.10) #####
      GIT_CHECKOUT: -b master origin/master
      MYSQL_DB_HOST: db
      VIRTUAL_HOST: dev.localtest.me   ##### need modify  #####
      VIRTUAL_ROOT: /var/www/CRM/src
#      ENABLE_HSTS: true
#      ENABLE_ACME: true               ##### letsencrypt setting
    volumes:
      - code:/var/www/CRM                     ##### code
      - ./keys/acme/:/acmecerts               #acme.sh install folder
      - ./keys/certs/:/etc/apache2/certs      #certs folder
      - ./setting/php-apache-dev/www.conf:/etc/apache2/sites-available/www.conf:ro
      - ./setting/php-apache-dev/ssl.conf:/etc/apache2/sites-available/ssl.conf:ro
      - ./setting/php-apache-dev/php.ini:/usr/local/etc/php/php.ini:ro
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      - ./setting/php-apache-dev/crmsetup:/usr/local/prechk
      - ./setting/php-apache-dev/app/:/app
      - ./secrets/BuildConfig.json:/var/www/BuildConfig.json    ##### need modify  #####
      - ./log/php-dev/:/usr/local/var/log     #debug use.
 #      - ./setting/nginx/dns_dynu.sh:/acme.sh/dnsapi/dns_dynu.sh   # fix dynu.sh issue
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - crm_secrets
      - ssl
#      - dns_api

  unison:
    container_name: unison
    image: eugenmayer/unison:2.51.2.1
    command: sh -c "chown -R xfs:xfs /unison && cd /unison && unison -socket 5000 >>/var/log/unison.log 2>&1"
    volumes:
      - code:/unison
    ports:
      - "5000:5000"

secrets:
  crm_secrets:
    file: ./secrets/crm_sql_secrets.json
#  dns_api:
#    file: ./secrets/dns_api.json           ##### need modify  #####
  ssl:
    file: ./secrets/ssl-dev.json            ##### need modify  #####

volumes:
  db-dev-volume: null
  code: null
