version: '3.5'
services:
  #### db use mysql as database
  db:
    container_name: db
    image: chrishsieh/mysql:latest
    volumes:
      #### database saved volume
      - db-dev-volume:/var/lib/mysql
      #### pre-script before service start, init CRM database
      - ./setting/sql/sql_setup:/usr/local/prechk
    ports:
      - "3306:3306"
    secrets:
      #### database secret setting
      - crm_secrets

  #### php run php and apache serivces
  php:
    container_name: php
    image: chrishsieh/php-apache-dev:latest
    links:
      - db
    environment:
      ##### do git ${_GIT_CMD} #####
      GIT_CMD: ${_DEV_GIT_CMD:-master}
      MYSQL_DB_HOST: db
      VIRTUAL_HOST: ${_DEV_VIRTUAL_HOST:-dev.localtest.me}   ##### need modify  #####
      VIRTUAL_ROOT: /var/www/CRM/src
      ENABLE_HSTS: ${_DEV_ENABLE_HSTS:-false}
      ENABLE_ACME: ${_DEV_ENABLE_ACME:-false}               ##### letsencrypt setting
    volumes:
      #### code
      - code:/var/www
      #### certs
      - ${_DEV_CERTS_FOLDER:-./keys}/acme/:/acmecerts               #acme.sh install folder
      - ${_DEV_CERTS_FOLDER:-./keys}/certs/:/etc/apache2/certs      #certs folder
      #### apache setting
      - ./setting/php-apache-dev/www.conf:/etc/apache2/sites-available/www.conf:ro
      - ./setting/php-apache-dev/ssl.conf:/etc/apache2/sites-available/ssl.conf:ro
      #### php setting
      - ./setting/php-apache-dev/php.ini:/usr/local/etc/php/php.ini:ro
      #### xdebug setting
      - ./setting/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      #### pre-script before service start, setting CRM
      - ./setting/php-apache-dev/crmsetup:/usr/local/prechk
      #### pre-script before service start, setting certs
      - ./setting/php-apache-dev/app/:/app
      #### CRM buildConfig setting
      - ${_DEV_CRM_BUILD_CONFIG:-./secrets/BuildConfig.json}:/var/BuildConfig.json
      #### php log file
      - ${_DEV_LOG_FOLDER:-./log}/php-dev/:/usr/local/var/log     #debug use.
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        #### setting for services call web server by host name
        aliases:
          - ${_DEV_VIRTUAL_HOST:-dev.localtest.me}
    secrets:
      - crm_secrets
      - ssl
      - dns_api

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  #### unison used for sync code to windows host
  unison:
    container_name: unison
    #### version need same as windows unison version.
    image: eugenmayer/unison:2.51.2.1
    command: "/entrypoint.sh supervisord"
    environment:
      APP_VOLUME: "/unison"
      UNISON_ARGS: "-socket 5000"
      OWNER_UID: 33
      UNISON_WATCH_ARGS: ""
      UNISON_SRC: ""
      UNISON_DEST: ""
      HOST_VOLUME: ""
      MONIT_ENABLE: "false"
    volumes:
      - code:/unison
    ports:
      - "5000:5000"
    restart: on-failure

  #### selenium used for web access
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"

secrets:
  #### database secret setting
  crm_secrets:
    file: ${_DEV_CRM_SRCRETS:-./secrets/crm_sql_secrets.json}
  #### for DNS server auto api setting.
  dns_api:
    file: ${_DEV_DNS_API_SRCRETS:-./secrets/dns_api.json}
  #### cert setting.
  ssl:
    file: ${_DEV_SSL_SRCRETS:-./secrets/ssl-dev.json}

volumes:
  #### database data volume
  db-dev-volume: null
  #### code volume used for sync
  code: null
