#!/bin/bash

set -e

if ! [ -f ./CRM/churchcrm/index.php ]; then
    if [ "${RELEASE_VERSION}" == "latest" ]; then
        crmlatest=$(curl -s https://api.github.com/repos/churchCRM/CRM/releases/latest | grep "browser_download_url.*zip" | cut -d '"' -f 4);
    else
        crmlatest="https://github.com/ChurchCRM/CRM/releases/download/${RELEASE_VERSION}/ChurchCRM-${RELEASE_VERSION}.zip";
    fi
    wget $crmlatest && \
    unzip -q -o *.zip -d CRM/ && \
    rm -rf *.zip && \
    chown -R www-data:www-data CRM
fi

if ! [ -f ./CRM/churchcrm/Include/Config.php ]; then
    cp /var/www/CRM/churchcrm/Include/Config.php.example /var/www/CRM/churchcrm/Include/Config.php
    chown www-data:www-data /var/www/CRM/churchcrm/Include/Config.php
    chmod 777 /var/www/CRM/churchcrm/Include/Config.php

    # Import Docker Secrets
    MYSQL_USER=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER')
    MYSQL_USER_PWD=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER_PWD')
    MYSQL_USER_DB=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER_DB')

    if [ $MYSQL_USER_PWD = "changeme" ]; then
        red=$(tput setaf 1)    # Red
        reset=$(tput sgr0)
        echo "${red}*********************************************"
        echo "${red}WARNING!!!"
        echo "${red}YOU DID NOT CHANGE THE MYSQL_USER_PWD IN THE crm_secrets.json FILE!!!"
        echo "${red}This is EXTREMELY insecure. Please go back and change the password to something more secure and re-build your images by running docker-compose build"
        echo "${red}*********************************************"
        echo "$(tput sgr0)"
        exit 1
    fi

    # Create ChurchCRM Config File
    sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||DB_SERVER_PORT||/3306/g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||DB_NAME||/$MYSQL_USER_DB/g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||DB_USER||/$MYSQL_USER/g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||DB_PASSWORD||/$MYSQL_USER_PWD/g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||URL||//g" /var/www/CRM/churchcrm/Include/Config.php
    sed -i "s/||ROOT_PATH||//g" /var/www/CRM/churchcrm/Include/Config.php
fi
