#!/bin/bash

if ! [ -f ./CRM/src/index.php ]; then
    cd CRM && \
    git fetch --all && \
    git reset --hard origin/master && \
    chmod +x ./travis-ci/*.sh && \
    chmod +x ./scripts/*.sh
    npm install --unsafe-perm
    npm run composer-install
    npm run orm-gen
    npm run install
    npm run update-signatures
    chown -R www-data:www-data /var/www/CRM
fi

if ! [ -f ./CRM/src/Include/Config.php ]; then
    cp /var/www/CRM/src/Include/Config.php.example /var/www/CRM/src/Include/Config.php
    chown www-data:www-data /var/www/CRM/src/Include/Config.php
    chmod 777 /var/www/CRM/src/Include/Config.php

    # Import Docker Secrets
    MYSQL_USER=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER')
    MYSQL_USER_PWD=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER_PWD')
    MYSQL_USER_DB=$(cat /run/secrets/crm_secrets | jq -r '.mysql.MYSQL_USER_DB')
    if [ $MYSQL_USER_PWD = "changeme" ]; then
        figlet -f colossal "WARNING"
        red=$(tput setaf 1) # Red
        reset=$(tput sgr0)
        echo "${red}*********************************************"
        echo "${red}WARNING!!!"
        echo "${red}YOU DID NOT CHANGE THE MYSQL_USER_PWD IN THE crm_secrets.json FILE!!!"
        echo "${red}This is EXTREMELY insecure. Please go back and change the password to something more secure and re-build your images by running `docker-compose build`"
        echo "${red}*********************************************"
        ${reset}
        echo ""
    fi
    # Create ChurchCRM Config File
    sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||DB_SERVER_PORT||/3306/g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||DB_NAME||/$MYSQL_USER_DB/g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||DB_USER||/$MYSQL_USER/g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||DB_PASSWORD||/$MYSQL_USER_PWD/g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||URL||//g" /var/www/CRM/src/Include/Config.php
    sed -i "s/||ROOT_PATH||//g" /var/www/CRM/src/Include/Config.php
fi
